version: "3.8"
services:
  # server:
  #   image: autorender:latest
  #   build:
  #     context: .
  #   container_name: "${PROJECT_NAME}-server"
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "127.0.0.1:${HTTP_PORT}:80"
  #   links:
  #     - database:database
  #   volumes:
  #     - ./src/server:/app:rw
  database:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}-db"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
