version: "3.8"
services:
  server:
    image: "${PROJECT_NAME}-server"
    build:
      context: .
      target: server
    container_name: "${PROJECT_NAME}-server"
    restart: always
    links:
      - database:${PROJECT_NAME}.database
    environment:
      DENO_TASK_ENTRYPOINT: ${DENO_TASK_ENTRYPOINT}
    volumes:
      - ./docker/logs/server:/app/log/server:rw
      - ./src/server:/app:rw
      - ./src/shared:/shared:rw
  bot:
    image: "${PROJECT_NAME}-bot"
    build:
      context: .
      target: bot
    container_name: "${PROJECT_NAME}-bot"
    restart: always
    links:
      - server:${PROJECT_NAME}.server
    environment:
      DENO_TASK_ENTRYPOINT: ${DENO_TASK_ENTRYPOINT}
    volumes:
      - ./docker/logs/bot:/app/log/bot:rw
      - ./src/bot:/app:rw
      - ./src/shared:/shared:rw
  database:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}-db"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
  proxy:
    profiles: ["nginx"]
    image: nginx:stable-alpine
    container_name: "${PROJECT_NAME}-proxy"
    links:
      - server:${PROJECT_NAME}.server
    ports:
      - 443:443
    environment:
      - NGINX_HOST=${SERVER_NAME}
      - NGINX_PORT=443
      - SERVER_PORT=${SERVER_PORT}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ./docker/ssl:/ssl:r
      - ./docker/nginx:/etc/nginx/templates
      - ./docker/logs/nginx:/var/log/nginx:rw
