update maps set alias = "Tramride", best_time_id = 1 where game_id = 4 and name = "st_a1_tramride";
update maps set alias = "Mel Intro", best_time_id = 2 where game_id = 4 and name = "st_a1_mel_intro";
update maps set alias = "Lift", best_time_id = 3 where game_id = 4 and name = "st_a1_lift";
update maps set alias = "Garden", best_time_id = 4 where game_id = 4 and name = "st_a1_garden";
update maps set alias = "Destroyed Garden", best_time_id = 5 where game_id = 4 and name = "st_a2_garden_de";
update maps set alias = "Underbounce", best_time_id = 6 where game_id = 4 and name = "st_a2_underbounce";
update maps set alias = "Once Upon", best_time_id = 7 where game_id = 4 and name = "st_a2_once_upon";
update maps set alias = "Past Power", best_time_id = 8 where game_id = 4 and name = "st_a2_past_power";
update maps set alias = "Ramp", best_time_id = 9 where game_id = 4 and name = "st_a2_ramp";
update maps set alias = "Firestorm", best_time_id = 10 where game_id = 4 and name = "st_a2_firestorm";
update maps set alias = "Junkyard", best_time_id = 11 where game_id = 4 and name = "st_a3_junkyard";
update maps set alias = "Concepts", best_time_id = 12 where game_id = 4 and name = "st_a3_concepts";
update maps set alias = "Paint Fling", best_time_id = 13 where game_id = 4 and name = "st_a3_paint_fling";
update maps set alias = "Faith Plate", best_time_id = 14 where game_id = 4 and name = "st_a3_faith_plate";
update maps set alias = "Transition", best_time_id = 15 where game_id = 4 and name = "st_a3_transition";
update maps set alias = "Overgrown", best_time_id = 16 where game_id = 4 and name = "st_a4_overgrown";
update maps set alias = "Funnel Over Goo", best_time_id = 17 where game_id = 4 and name = "st_a4_tb_over_goo";
update maps set alias = "Two Of A Kind", best_time_id = 18 where game_id = 4 and name = "st_a4_two_of_a_kind";
update maps set alias = "Destroyed", best_time_id = 19 where game_id = 4 and name = "st_a4_destroyed";
update maps set alias = "Factory", best_time_id = 20 where game_id = 4 and name = "st_a4_factory";
update maps set alias = "Core Access", best_time_id = 21 where game_id = 4 and name = "st_a4_core_access";
update maps set alias = "Finale", best_time_id = 22 where game_id = 4 and name = "st_a4_finale";
update maps set alias = "Advanced Tramride", best_time_id = 23 where game_id = 4 and name = "sp_a1_tramride";
update maps set alias = "Advanced Mel Intro", best_time_id = 24 where game_id = 4 and name = "sp_a1_mel_intro";
update maps set alias = "Advanced Lift", best_time_id = 25 where game_id = 4 and name = "sp_a1_lift";
update maps set alias = "Advanced Garden", best_time_id = 26 where game_id = 4 and name = "sp_a1_garden";
update maps set alias = "Advanced Destroyed Garden", best_time_id = 27 where game_id = 4 and name = "sp_a2_garden_de";
update maps set alias = "Advanced Underbounce", best_time_id = 28 where game_id = 4 and name = "sp_a2_underbounce";
update maps set alias = "Advanced Once Upon", best_time_id = 29 where game_id = 4 and name = "sp_a2_once_upon";
update maps set alias = "Advanced Past Power", best_time_id = 30 where game_id = 4 and name = "sp_a2_past_power";
update maps set alias = "Advanced Ramp", best_time_id = 31 where game_id = 4 and name = "sp_a2_ramp";
update maps set alias = "Advanced Firestorm", best_time_id = 32 where game_id = 4 and name = "sp_a2_firestorm";
update maps set alias = "Advanced Junkyard", best_time_id = 33 where game_id = 4 and name = "sp_a3_junkyard";
update maps set alias = "Advanced Concepts", best_time_id = 34 where game_id = 4 and name = "sp_a3_concepts";
update maps set alias = "Advanced Paint Fling", best_time_id = 35 where game_id = 4 and name = "sp_a3_paint_fling";
update maps set alias = "Advanced Faith Plate", best_time_id = 36 where game_id = 4 and name = "sp_a3_faith_plate";
update maps set alias = "Advanced Transition", best_time_id = 37 where game_id = 4 and name = "sp_a3_transition";
update maps set alias = "Advanced Overgrown", best_time_id = 38 where game_id = 4 and name = "sp_a4_overgrown";
update maps set alias = "Advanced Funnel Over Goo", best_time_id = 39 where game_id = 4 and name = "sp_a4_tb_over_goo";
update maps set alias = "Advanced Two Of A Kind", best_time_id = 40 where game_id = 4 and name = "sp_a4_two_of_a_kind";
update maps set alias = "Advanced Destroyed", best_time_id = 41 where game_id = 4 and name = "sp_a4_destroyed";
update maps set alias = "Advanced Factory", best_time_id = 42 where game_id = 4 and name = "sp_a4_factory";
update maps set alias = "Advanced Core Access", best_time_id = 43 where game_id = 4 and name = "sp_a4_core_access";
update maps set alias = "Advanced Finale", best_time_id = 44 where game_id = 4 and name = "sp_a4_finale";
