version: "3.8"
services:
  server:
    image: "${PROJECT_NAME}-server"
    build:
      context: .
      target: server
    container_name: "${PROJECT_NAME}-server"
    restart: always
    links:
      - database:${PROJECT_NAME}.database
    ports:
      - "127.0.0.1:${HTTP_PORT}:8001"
      - "127.0.0.1:${HTTPS_PORT}:8001"
    extra_hosts: 
      - ${SERVER_NAME}:127.0.0.1
    environment:
      DENO_TASK_ENTRYPOINT: ${DENO_TASK_ENTRYPOINT}
    volumes:
      - ./docker/logs/server:/app/log/server:rw
      - ./src/server/.env:/app/.env:rw
      - ./src/server/storage:/app/storage:rw
  bot:
    image: "${PROJECT_NAME}-bot"
    build:
      context: .
      target: bot
    container_name: "${PROJECT_NAME}-bot"
    restart: always
    links:
      - server:${PROJECT_NAME}.server
    environment:
      DENO_TASK_ENTRYPOINT: ${DENO_TASK_ENTRYPOINT}
    volumes:
      - ./docker/logs/bot:/app/log/bot:rw
      - ./docker/volumes/kv:/kv:rw
      - ./src/bot/.env:/app/.env:rw
  database:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}-db"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
