version: "3.8"
services:
  server:
    image: "${PROJECT_NAME}-server"
    build:
      context: .
      target: server
    container_name: "${PROJECT_NAME}-server"
    restart: always
    ports:
      - '127.0.0.1:9229:9229'
    links:
      - database:autorender.database
    volumes:
      - ./docker/volumes/logs/server:/logs/server:rw
      - ./docker/volumes/storage:/storage:rw
      - ./docker/volumes/.env.server:/app/.env:rw
      - ./docker/volumes/entrypoint.server.sh:/app/entrypoint.sh:rw
      - ./src/server:/app:rw
      - ./src/shared:/shared:rw
  bot:
    image: "${PROJECT_NAME}-bot"
    build:
      context: .
      target: bot
    container_name: "${PROJECT_NAME}-bot"
    restart: always
    ports:
      - '127.0.0.1:9230:9229'
    links:
      - server:autorender.server
    volumes:
      - ./docker/volumes/logs/bot:/logs/bot:rw
      - ./docker/volumes/kv:/kv:rw
      - ./docker/volumes/.env.bot:/app/.env:rw
      - ./docker/volumes/entrypoint.bot.sh:/app/entrypoint.sh:rw
      - ./src/bot:/app:rw
      - ./src/shared:/shared:rw
  database:
    image: mariadb:11
    container_name: "${PROJECT_NAME}-db"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - ./docker/volumes/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
      - ./docker/volumes/backups:/backups
  proxy:
    image: nginx:stable-alpine3.17
    container_name: "${PROJECT_NAME}-proxy"
    links:
      - server:autorender.server
    ports:
      - 443:443
    environment:
      - NGINX_HOST=autorender.portal2.local
      - NGINX_PORT=443
    volumes:
      - ./docker/volumes/ssl:/ssl:r
      - ./docker/volumes/nginx:/etc/nginx/templates
      - ./docker/volumes/logs/nginx:/var/log/nginx:rw
      - ./docker/volumes/storage:/storage:r
  board-server:
    image: p2sr/mel-board:latest
    container_name: "board-server"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:8880:80"
      - "127.0.0.1:4443:443"
    links:
      - board-database:database
    volumes:
      - ./board-net/.config.json:/var/www/html/.config.json
      - ./board-net/docker/apache/board.portal2.local.conf:/etc/apache2/sites-available/board.portal2.local.conf
      - ./board-net/docker/logs/error.log:/var/log/apache2/error.log
      - ./board-net/docker/logs/access.log:/var/log/apache2/other_vhosts_access.log
      - ./board-net/docker/logs/debug.txt:/var/www/html/debug.txt
      - ./board-net/docker/php/board.ini:/etc/php/8.1/apache2/conf.d/board.ini
      - ./board-net/docker/ssl/board.portal2.local.key:/etc/apache2/ssl/board.portal2.local.key
      - ./board-net/docker/ssl/board.portal2.local.crt:/etc/apache2/ssl/board.portal2.local.crt
  board-database:
    image: mysql:8
    container_name: "board-db"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: board
      MYSQL_PASSWORD: board
      MYSQL_DATABASE: board
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./board-net/docker/initdb:/docker-entrypoint-initdb.d
      - ./board-net/docker/volumes/mysql:/var/lib/mysql
      - ./board-net/docker/volumes/backups:/backups
