name: Deploy

on:
  workflow_dispatch:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno task check:types

      # Disabled until useful tests have been written
      #- name: Test
      #  run: deno test -A

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bot image
        uses: docker/build-push-action@v4
        with:
          push: true
          target: bot
          tags: p2sr/autorender-bot:latest,p2sr/autorender-bot:1.0.0

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          push: true
          target: server
          tags: p2sr/autorender-server:latest,p2sr/autorender-server:1.0.0
